apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix
  labels:
    app: netflix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netflix
  template:
    metadata:
      labels:
        app: netflix
    spec:
      containers:
        - name: netflix
          image: swarajwohlig2107/netflix:main-c7f5f45f190432d99a4592ba89942f446595d140
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: netflix-config
