apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-api
  labels:
    app: sample-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-api
  template:
    metadata:
      labels:
        app: sample-api
    spec:
      containers:
        - name: sample-api
          image: swarajwohlig2107/sample:main-f82c0f9fdd3dfe6c2990b776c6aacd4b430123c6
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: sample-config
