apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-api
  labels:
    app: sample-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-api
  template:
    metadata:
      labels:
        app: sample-api
    spec:
      containers:
        - name: sample-api
          image: swarajwohlig2107/sample:main-7baf37a213d9709ff7dcc8987e3253a1d02f2041
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: sample-config
