apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix
  labels:
    app: netflix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netflix
  template:
    metadata:
      labels:
        app: netflix
    spec:
      containers:
        - name: netflix
          image: swarajwohlig2107/netflix:main-329bdfcd088f582e7d47589d0278d6bf7f78dd37
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: netflix-config
