apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix
  labels:
    app: netflix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netflix
  template:
    metadata:
      labels:
        app: netflix
    spec:
      containers:
        - name: netflix
          image: swarajwohlig2107/netflix:main-3a6dfd226f718560746d3116d73f411c36fef01b
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: netflix-config
