apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-api
  labels:
    app: sample-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-api
  template:
    metadata:
      labels:
        app: sample-api
    spec:
      containers:
        - name: sample-api
          image: 'asia-south1-docker.pkg.dev/confixa-rnd/cloud-deploy/my-test:c7986a99d7b33e6815b58e71587254e2beb6de16'
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: sample-config
