apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix
  labels:
    app: netflix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netflix
  template:
    metadata:
      labels:
        app: netflix
    spec:
      containers:
        - name: netflix
          image: swarajwohlig2107/netflix:main-397591d314d7c2d8c9988c910c4d1cda0983fb54
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: netflix-config
