apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-api
  labels:
    app: sample-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-api
  template:
    metadata:
      labels:
        app: sample-api
    spec:
      containers:
        - name: sample-api
          image: swarajwohlig2107/sample:main-244a48dd43580143222129c919ffeb2a4eb00652
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: sample-config
