apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: olympic-api
  labels:
    app: olympic-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: olympic-api
  template:
    metadata:
      labels:
        app: olympic-api
    spec:
      containers:
      - name: olympic-api
        image: swarajwohlig2107/olympic-api
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: olympic-api-config