apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: sample-api
  labels:
    app: sample-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-api
  template:
    metadata:
      labels:
        app: sample-api
    spec:
      containers:
        - name: sample-api
          image: swarajwohlig2107/sample:$GITHUB_REF-$GITHUB_SHA
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: sample-api-config
